manual-reg.yml gabung ke regression.yml prerelease-reg.yml gabung ke prerelease.yml

diff --git a/workflow-templates/prerelease.yml b/workflow-templates/prerelease.yml
--- a/workflow-templates/prerelease.yml
+++ b/workflow-templates/prerelease.yml
@@ -2,16 +2,19 @@ name: "Post-Integration: Prerelease"
 
 on:
   pull_request:
-    branches: [ $default-branch ]
-    types: [ closed ]
+    branches:
+      - master
+    types: closed
 
 jobs:
+
   prerelease:
     runs-on: ubuntu-20.04
     if: github.event.pull_request.merged == true
     outputs:
       key: ${{ steps.prerelease-tag.outputs.key }}
     steps:
+      - run: echo head_ref is ${{ github.head_ref }} | cut -d'/' -f 2
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
@@ -28,4 +31,95 @@ jobs:
       name: staging:${{ needs.prerelease.outputs.key }}
       url: https://${{ needs.prerelease.outputs.key }}.example.com
     steps:
-      - run: echo 'Deployed'
+      - run: |
+          echo 'Deployed'
+          echo the branch name is ${{ needs.prerelease.outputs.key }}
+
+  regression:
+    needs: [prerelease, deploy]
+    runs-on: ubuntu-20.04
+    env:
+      # Repository of regression test in format <organization>/<repository>.
+      REPOSITORY: ""
+      # Maven project under monorepo of regression test.
+      PROJECT: ""
+      # Domain of URL for accesing the env 
+      DOMAIN: ""
+      TICKET: "${{ needs.prerelease.outputs.key }}"
+      STG_ENV: "https://${{ needs.prerelease.outputs.key }}.example.com"
+    steps:
+      - name: Check if variable is empty
+        run: |
+          if [ -z "${REPOSITORY}" ]; then
+            echo "::error::'REPOSITORY' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${PROJECT}" ]; then
+            echo "::error::'PROJECT' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${DOMAIN}" ]; then
+            echo "::error::'DOMAIN' environment variable must be set"
+            exit 1
+          fi
+      - uses: actions/checkout@v2
+        with:
+          repository: ${{ env.REPOSITORY }}
+          ref: master
+          token: ${{ secrets.REGRESSION_PAT }}
+
+      - name: Set up JDK 1.8
+        uses: actions/setup-java@v1
+        with:
+          java-version: 1.8
+
+      - name: Cache local Maven repository
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '${{ env.PROJECT }}/pom.xml') }}
+          restore-keys: ${{ runner.os }}-maven-
+
+      # Set report portal parameters environment variables
+      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
+      # - name: Set Report Portal Parameters
+      #   run: |
+      #     NOW=$(date +%d%m%Y)
+      #     echo "rp.description='Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}'" >> $GITHUB_ENV
+      #     echo "rp.attributes=release:${NOW}" >> $GITHUB_ENV
+      - name: Run Regression
+        run: |
+          NOW=$(date +%d%m%Y)
+          mvn -pl ${PROJECT} verify -q \
+          -Dwebdriver.base.url=${STG_ENV} \
+          -Drp.endpoint=${{ secrets.RP_ENDPOINT }} \
+          -Drp.api.key=${{ secrets.RP_API_KEY }} \
+          -Drp.description="Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}" \
+          -Drp.attributes=release:${NOW}
+        # env:
+        #   rp.endpoint: ${{ secrets.RP_ENDPOINT }}
+        #   rp.api.key: ${{ secrets.RP_API_KEY }}
+
+      # Optional. It will take some artifact storage quota.
+      # Disable if dont needed.
+      - name: Uploading Result Data
+        if: ${{ success() || failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: Result
+          path: ${{ env.PROJECT }}/target/site
+
+      # Need Zephyr Scale Key preconfigured.
+      - name: Sending Result to Zephyr Scale
+        if: ${{ success() || failure() }}
+        env:
+          ZEPHYR_API_KEY: ${{ secrets.TM4J_KEY }}
+          PROJECT_KEY: ABCD
+          JSON_PATH: ${{ env.PROJECT }}/target/cucumber-parallel/*.json
+        run: |
+          zip result.zip $JSON_PATH
+          curl --request POST \
+            --url "https://api.adaptavist.io/tm4j/v2/automations/executions/cucumber?projectKey=$PROJECT_KEY&autoCreateTestCases=false" \
+            --header "Authorization: Bearer $ZEPHYR_API_KEY" \
+            --header 'content-type: multipart/form-data' \
+            --form "file=@result.zip;type=application/x-zip-compressed"
