adding ingress config

diff --git a/workflow-templates/prerelease.yml b/workflow-templates/prerelease.yml
--- a/workflow-templates/prerelease.yml
+++ b/workflow-templates/prerelease.yml
@@ -27,21 +27,87 @@ jobs:
     if: needs.prerelease.outputs.key
     environment:
       name: staging:${{ needs.prerelease.outputs.key }}
-      url: https://${{ needs.prerelease.outputs.key }}.example.com      
+      url: https://${{ secrets.SYSTEM_NAME }}-${{ needs.prerelease.outputs.key }}.${{ secrets.DOMAIN }}     
     env:
-      # Your system name ex: proteus-core
+      # Your system name for example proteus-core
       SYSTEM_NAME: ""
-      #Env URL
+      # Environment URL
       URL: "$SYSTEM_NAME-${{ needs.prerelease.outputs.key }}.${{ secrets.DOMAIN }}"
       # Kubernetes endpoint/ingress IP address
       INGRESS_ENDPOINT: ""
+      #AWS EKS cluster region
+      AWS_CLUSTER_REGION: ""
+      #AWS EKS cluster name
+      AWS_CLUSTER_NAME: ""
+      #Kubernetes namespace
+      K8S_NAMESPACE: ""
+      # Kubernetes whitelist ip address
+      K8S_WHITELIST_IP: ""
+      # Kubernetes service name
+      K8S_SERVICE_NAME: ""
+      #Kubernetes service port
+      K8S_SERVICE_PORT: ""
     steps:
+      - name: Check if variable is empty
+        run: |
+          if [ -z "${SYSTEM_NAME}" ]; then
+            echo "::error::'SYSTEM_NAME' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${INGRESS_ENDPOINT}" ]; then
+            echo "::error::'INGRESS_ENDPOINT' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${AWS_CLUSTER_REGION}" ]; then
+            echo "::error::'AWS_CLUSTER_REGION' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${AWS_CLUSTER_NAME}" ]; then
+            echo "::error::'AWS_CLUSTER_NAME' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${K8S_NAMESPACE}" ]; then
+            echo "::error::'K8S_NAMESPACE' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${K8S_WHITELIST_IP}" ]; then
+            echo "::error::'K8S_WHITELIST_IP' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${K8S_SERVICE_NAME}" ]; then
+            echo "::error::'K8S_SERVICE_NAME' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${K8S_SERVICE_PORT}" ]; then
+            echo "::error::'K8S_SERVICE_PORT' environment variable must be set"
+            exit 1
+          fi
       - run: echo 'Deployed'
-      - name: Configure AWS credentials
+      # Configure AWS Credentials for EKS
+      - run: |
+          aws configure set aws_access_key_id $EKS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $EKS_SECRET_ACCESS_KEY
+        env:
+          EKS_ACCESS_KEY_ID: ${{ secrets.EKS_ALTERRA_ID_ACCESS_KEY_ID }}
+          EKS_SECRET_ACCESS_KEY: ${{ secrets.EKS_ALTERRA_ID_SECRET_ACCESS_KEY }}
+      - name: Create kubeconfig
+        run: |
+          brew install aws-iam-authenticator
+          aws eks --region $AWS_CLUSTER_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
+      - uses: sepulsa/post-integration-action/create-ingress@ingress-standalone
+        with:
+          name: $SYSTEM_NAME-${{ needs.prerelease.outputs.key }}
+          namespace: $K8S_NAMESPACE
+          whitelist-ip: $K8S_WHITELIST_IP
+          host: $SYSTEM_NAME-${{ needs.prerelease.outputs.key }}.${{ secrets.DOMAIN }}
+          service-name: $K8S_SERVICE_NAME
+          service-port: $K8S_SERVICE_PORT      
+
+      - name: Configure AWS credentials for Route53
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
       - id: create-domain
         uses: sepulsa/post-integration-action/route-domain@main
@@ -49,11 +115,8 @@ jobs:
           action: CREATE
           name: $SYSTEM_NAME-${{ needs.prerelease.outputs.key }}.${{ secrets.DOMAIN }}
           type: CNAME
-          dns-record: ${{ secrets.INGRESS_ENDPOINT }}
+          dns-record: $INGRESS_ENDPOINT
           zone-id: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
-      - name: Environment URL
-        run: |
-          echo $URL
        
 
   regression:
@@ -66,6 +129,8 @@ jobs:
       PROJECT: ""
       # Domain of URL for accesing the env 
       DOMAIN: ""
+      # Your system name for example proteus-core
+      SYSTEM_NAME: ""
       TICKET: "${{ needs.prerelease.outputs.key }}"
     steps:
       - name: Check if variable is empty
@@ -78,6 +143,10 @@ jobs:
             echo "::error::'PROJECT' environment variable must be set"
             exit 1
           fi
+          if [ -z "${SYSTEM_NAME}" ]; then
+            echo "::error::'NAME' environment variable must be set"
+            exit 1
+          fi
           if [ -z "${DOMAIN}" ]; then
             echo "::error::'DOMAIN' environment variable must be set"
             exit 1
@@ -85,7 +154,7 @@ jobs:
 
       - name: Set Environment URL
         run: |
-          echo "STG_ENV=https://${{ github.event.inputs.key }}.${DOMAIN}" >> $GITHUB_ENV
+          echo "STG_ENV=https://${SYSTEM_NAME}-${{ needs.prerelease.outputs.key }}.${DOMAIN}" >> $GITHUB_ENV
 
       - uses: actions/checkout@v2
         with:
