manual-reg.yml gabung ke regression.yml prerelease-reg.yml gabung ke prerelease.yml

diff --git a/workflow-templates/regression.yml b/workflow-templates/regression.yml
--- a/workflow-templates/regression.yml
+++ b/workflow-templates/regression.yml
@@ -1,15 +1,24 @@
 name: "Post-Integration: Regression Test"
 
 on:
-  push:
-    branches: [ $default-branch ]
+  # push event won't be used, because the env has to be deployed before running the regression 
+  # push:
+  #   branches: [ $default-branch ]
   workflow_dispatch:
+    inputs:
+      key:
+        required: true
+        description: 'The JIRA Issue Key'
 
 env:
   # Repository of regression test in format <organization>/<repository>.
   REPOSITORY: ""
   # Maven project under monorepo of regression test.
   PROJECT: ""
+  # Domain of URL for accesing the env 
+  DOMAIN: ""
+  TICKET: "${{ github.event.inputs.key }}"
+  STG_ENV: "https://${{ github.event.inputs.key }}.${{ env.DOMAIN }}"
 
 jobs:
   test:
@@ -24,6 +33,10 @@ jobs:
           fi
           if [ -z "${PROJECT}" ]; then
             echo "::error::'PROJECT' environment variable must be set"
+            exit 1
+          fi
+          if [ -z "${DOMAIN}" ]; then
+            echo "::error::'DOMAIN' environment variable must be set"
             exit 1
           fi
 
@@ -47,17 +60,23 @@ jobs:
 
       # Set report portal parameters environment variables
       # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
-      - name: Set Report Portal Parameters
-        run: |
-          NOW=$(date +%d%m%Y)
-          echo "rp.description='Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}'" >> $GITHUB_ENV
-          echo "rp.attributes=release:${NOW}" >> $GITHUB_ENV
+      # - name: Set Report Portal Parameters
+      #   run: |
+      #     NOW=$(date +%d%m%Y)
+      #     echo "rp.description='Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}'" >> $GITHUB_ENV
+      #     echo "rp.attributes=release:${NOW}" >> $GITHUB_ENV
 
       - name: Run Regression
-        run: mvn -pl ${PROJECT} verify -q
-        env:
-          rp.endpoint: ${{ secrets.RP_ENDPOINT }}
-          rp.api.key: ${{ secrets.RP_API_KEY }}
+        run: |
+          mvn -pl ${PROJECT} verify -q \
+          -Dwebdriver.base.url=${STG_ENV} \
+          -Drp.endpoint=${{ secrets.RP_ENDPOINT }} \
+          -Drp.api.key=${{ secrets.RP_API_KEY }} \
+          -Drp.description="Regression ${NOW} - Github Action #${GITHUB_RUN_NUMBER}" \
+          -Drp.attributes=release:${NOW}
+        # env:
+        #   rp.endpoint: ${{ secrets.RP_ENDPOINT }}
+        #   rp.api.key: ${{ secrets.RP_API_KEY }}
 
       # Optional. It will take some artifact storage quota.
       # Disable if dont needed.
@@ -67,6 +86,7 @@ jobs:
         with:
           name: Result
           path: ${{ env.PROJECT }}/target/site
+          retention-days: 3
 
       # Need Zephyr Scale Key preconfigured.
       - name: Sending Result to Zephyr Scale
